### ISSUE TITLE
Compatibility with `andThen` from ember-testing?

### ISSUE THREAD

**Issue by pmdarrow** [rwjblue/ember-cli-pretender#24]
I'm using Ember Data and I'd like to mock a response to a `model.save()` request using ember-cli-pretender. The issue I'm having is that when I do this, the `andThen` helper in ember-testing does not seem to wait for the `save()` promise to successfully resolve before executing the assertions handed to it and my tests fail. 

1. Is this the appropriate place for raising this issue? If not, what do you recommend is appropriate?
2. Can you suggest any workarounds?

**Comment by rwjblue** [comment]
From the description it seems unlikely that this is related to ember-cli-pretender. Most likely an issue or related to pretender itself. 

This is good news though since it means you should be able to create the issue in a JSBin.

**Comment by pmdarrow** [comment]
Turns out I was using the `andThen` helper without using the `click` helper to submit a form in my test. Pretender is working fine -- closing this issue.
