### ISSUE TITLE
[suggestion] Default install produces missing source map warning (ENOENT route-recognizer.js.map)

### ISSUE THREAD

**Issue by vire** [rwjblue/ember-cli-pretender#27]
Hi, would it make sense to add an dummy source map to route recognizer or to this addon? It's not very convenient to install some addon on an vanilla `ember new project` and get immediately and warning.

*Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/foo/bar//tmp/tree_merger-tmp_dest_dir-Uy6Uig0l.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'*

**Comment by lilfaf** [comment]
Same problem here. route-recognizer already has a fix [#45](https://github.com/tildeio/route-recognizer/commit/cc183c692f8e691227936028837c15b0910b1ea7)

**Comment by rwjblue** [comment]
I believe this is fixed by https://github.com/rwjblue/ember-cli-pretender/pull/39 (latest pretender depends on the newer router-recognizer).
