### ISSUE TITLE
Handle other deploy environments other than production

### ISSUE THREAD

**Issue by tim-evans** [rwjblue/ember-cli-pretender#37]
This line should probably be a user configured flag: https://github.com/rwjblue/ember-cli-pretender/blob/master/index.js#L13

We use the environment 'staging' for our apps. This addon makes it tricky to have identical staging and production builds for our apps.

**Comment by rwjblue** [comment]
Yep, agreed.  A user configurable option (defaulting to `production`) would be great.

**Comment by tim-evans** [comment]
Sure!

**Comment by tim-evans** [comment]
I'm going to make the option default to `app.tests`, since that seems to be the sanest default. Sounds good?

**Comment by rwjblue** [comment]
Yep, sounds great.
