### ISSUE TITLE
shim wont be needed shortly: 

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-cli-pretender#41]
https://github.com/pretenderjs/pretender/pull/96

**Comment by rwjblue** [comment]
This shim just loads that file via bower, I don't see an `ember-addon` main entry for it so we will need to continue to use this addon for now.

**Comment by stefanpenner** [comment]
the [shim](https://github.com/rwjblue/ember-cli-pretender/blob/master/vendor/ember-cli-pretender/shim.js) wont be needed shortyl

**Comment by rwjblue** [comment]
Fixed by https://github.com/rwjblue/ember-cli-pretender/pull/55.
