### ISSUE TITLE
v1.0.0 caused CI to fail

### ISSUE THREAD

**Issue by kellyselden** [rwjblue/ember-cli-pretender#57]
`BroccoliMergeTrees (ember-cli-pretender: treeForVendor): Expected Broccoli node, got undefined for inputNodes[0]`

https://github.com/kellyselden/package-hint-historic-resolver/pull/306
https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/189509702#L654

**Comment by rwjblue** [comment]
Awesome thank you for reporting, will dig in.

**Comment by kellyselden** [comment]
No prob. I feel guilty submitting such a tiny bug report, but then again greenkeeper takes the humanity out of it lol.

**Comment by rwjblue** [comment]
Fixed by https://github.com/rwjblue/ember-cli-pretender/pull/58

**Comment by kellyselden** [comment]
All good now. Thanks.
