### ISSUE TITLE
Allow disabling of fetch polyfill

### ISSUE THREAD

**Issue by mydea** [rwjblue/ember-cli-pretender#66]
For people that do not run their tests in old browsers (e.g. IE11) - like I guess a decent enough amount of people do - it would be great if you could disable the import of the fetch/abort controller polyfills.

Right now, it was very unexpected to me that a polyfill was installed in my development environment - maybe it would also be an idea to note that this is happening in the readme. And since we run our tests only in modern browsers, we could actually get rid of that.

**Comment by rwjblue** [comment]
Totally agreed, seems like a good fix (basically adding options for disabling as you suggested).
