### ISSUE TITLE
[question] should this be deprecated in favor of ember-auto-import?

### ISSUE THREAD

**Issue by gabrielcsapo** [rwjblue/ember-cli-pretender#74]
We are now using https://github.com/ef4/ember-auto-import and were able to use pretender directly. Should this be the path forward for anyone wanting to use pretender in the future?

**Comment by rwjblue** [comment]
Yep! Happy to accept a PR documenting that in the README and mentioning that this package is not needed.

**Comment by gabrielcsapo** [comment]
@rwjblue I opened up a PR to add this note to the README ✨
